[tool.poetry]
name = "vs studio mi primer python"
version = "0.1.0"
description = "my first project"
authors = ["kikehr"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
